const cards = [
    { id: 0, name: 'Шут', suit: null },
    { id: 1, name: 'Маг', suit: null },
    { id: 2, name: 'Верховная Жрица', suit: null },
    { id: 3, name: 'Императрица', suit: null },
    { id: 4, name: 'Император', suit: null },
    { id: 5, name: 'Иерофант', suit: null },
    { id: 6, name: 'Влюбленные', suit: null },
    { id: 7, name: 'Колесница', suit: null },
    { id: 8, name: 'Сила', suit: null },
    { id: 9, name: 'Отшельник', suit: null },
    { id: 10, name: 'Колесо Фортуны', suit: null },
    { id: 11, name: 'Справедливость', suit: null },
    { id: 12, name: 'Повешенный', suit: null },
    { id: 13, name: 'Смерть', suit: null },
    { id: 14, name: 'Умеренность', suit: null },
    { id: 15, name: 'Дьявол', suit: null },
    { id: 16, name: 'Башня', suit: null },
    { id: 17, name: 'Звезда', suit: null },
    { id: 18, name: 'Луна', suit: null },
    { id: 19, name: 'Солнце', suit: null },
    { id: 20, name: 'Суд', suit: null },
    { id: 21, name: 'Мир', suit: null },

    // Кубки
    { id: 'C1', name: 'Кубок 1', suit: 'Кубки' },
    { id: 'C2', name: 'Кубок 2', suit: 'Кубки' },
    { id: 'C3', name: 'Кубок 3', suit: 'Кубки' },
    { id: 'C4', name: 'Кубок 4', suit: 'Кубки' },
    { id: 'C5', name: 'Кубок 5', suit: 'Кубки' },
    { id: 'C6', name: 'Кубок 6', suit: 'Кубки' },
    { id: 'C7', name: 'Кубок 7', suit: 'Кубки' },
    { id: 'C8', name: 'Кубок 8', suit: 'Кубки' },
    { id: 'C9', name: 'Кубок 9', suit: 'Кубки' },
    { id: 'C10', name: 'Кубок 10', suit: 'Кубки' },
    { id: 'C11', name: 'Паж Кубков', suit: 'Кубки' },
    { id: 'C12', name: 'Рыцарь Кубков', suit: 'Кубки' },
    { id: 'C13', name: 'Королева Кубков', suit: 'Кубки' },
    { id: 'C14', name: 'Король Кубков', suit: 'Кубки' },

    // Пентакли
    { id: 'P1', name: 'Пентакль 1', suit: 'Пентакли' },
    { id: 'P2', name: 'Пентакль 2', suit: 'Пентакли' },
    { id: 'P3', name: 'Пентакль 3', suit: 'Пентакли' },
    { id: 'P4', name: 'Пентакль 4', suit: 'Пентакли' },
    { id: 'P5', name: 'Пентакль 5', suit: 'Пентакли' },
    { id: 'P6', name: 'Пентакль 6', suit: 'Пентакли' },
    { id: 'P7', name: 'Пентакль 7', suit: 'Пентакли' },
    { id: 'P8', name: 'Пентакль 8', suit: 'Пентакли' },
    { id: 'P9', name: 'Пентакль 9', suit: 'Пентакли' },
    { id: 'P10', name: 'Пентакль 10', suit: 'Пентакли' },
    { id: 'P11', name: 'Паж Пентаклей', suit: 'Пентакли' },
    { id: 'P12', name: 'Рыцарь Пентаклей', suit: 'Пентакли' },
    { id: 'P13', name: 'Королева Пентаклей', suit: 'Пентакли' },
    { id: 'P14', name: 'Король Пентаклей', suit: 'Пентакли' },

    // Мечи
    { id: 'S1', name: 'Меч 1', suit: 'Мечи' },
    { id: 'S2', name: 'Меч 2', suit: 'Мечи' },
    { id: 'S3', name: 'Меч 3', suit: 'Мечи' },
    { id: 'S4', name: 'Меч 4', suit: 'Мечи' },
    { id: 'S5', name: 'Меч 5', suit: 'Мечи' },
    { id: 'S6', name: 'Меч 6', suit: 'Мечи' },
    { id: 'S7', name: 'Меч 7', suit: 'Мечи' },
    { id: 'S8', name: 'Меч 8', suit: 'Мечи' },
    { id: 'S9', name: 'Меч 9', suit: 'Мечи' },
    { id: 'S10', name: 'Меч 10', suit: 'Мечи' },
    { id: 'S11', name: 'Паж Мечей', suit: 'Мечи' },
    { id: 'S12', name: 'Рыцарь Мечей', suit: 'Мечи' },
    { id: 'S13', name: 'Королева Мечей', suit: 'Мечи' },
    { id: 'S14', name: 'Король Мечей', suit: 'Мечи' },

    // Жезлы
    { id: 'W1', name: 'Жезл 1', suit: 'Жезлы' },
    { id: 'W2', name: 'Жезл 2', suit: 'Жезлы' },
    { id: 'W3', name: 'Жезл 3', suit: 'Жезлы' },
    { id: 'W4', name: 'Жезл 4', suit: 'Жезлы' },
    { id: 'W5', name: 'Жезл 5', suit: 'Жезлы' },
    { id: 'W6', name: 'Жезл 6', suit: 'Жезлы' },
    { id: 'W7', name: 'Жезл 7', suit: 'Жезлы' },
    { id: 'W8', name: 'Жезл 8', suit: 'Жезлы' },
    { id: 'W9', name: 'Жезл 9', suit: 'Жезлы' },
    { id: 'W10', name: 'Жезл 10', suit: 'Жезлы' },
    { id: 'W11', name: 'Паж Жезлов', suit: 'Жезлы' },
    { id: 'W12', name: 'Рыцарь Жезлов', suit: 'Жезлы' },
    { id: 'W13', name: 'Королева Жезлов', suit: 'Жезлы' },
    { id: 'W14', name: 'Король Жезлов', suit: 'Жезлы' },
];

export default cards;
